default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: bartosz
  password: 123

development:
  <<: *default
  database: website_position_development

test:
  <<: *default
  database: website_position_test

production:
  <<: *default
  database: website_position_production
  username: website_position
  password: <%= ENV['WEBSITE_POSITION_DATABASE_PASSWORD'] %>
